import { ReactNode } from "react";
import "./globals.css";
import Providers from "@/components/providers";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * RootLayout is the top-level layout component for the application.
 * It wraps all child components inside the global application context.
 *
 * @param children - The components that will be rendered within this layout.
 * @returns The rendered children within the root layout.
 */
export default function RootLayout({ children }: Readonly<{ children: ReactNode }>) {
    return children;
}
